services:
  db:
    image: postgres:15
    container_name: rural_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rural_manager
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: rural_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: rural_manager
    command: npm run start:prod

  seed:
    image: node:18
    depends_on:
      - app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    entrypoint: ["sh", "-c", "sleep 10 && npm install && npm run seed"]
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: rural_manager

  e2e:
    image: node:18
    depends_on:
      - seed
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    entrypoint: ["sh", "-c", "sleep 5 && npm install && npm run test:e2e"]
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: rural_manager

volumes:
  pgdata:
